RPY-1216: Create survey component with emoji, stars, and simple survey variants
tunaiku/tunaiku-ui-web pull request #15
Opened 2023-02-16 08:36 UTC by lekhasholehati

### Description
Create a new survey component base this requirement: [Link ZeroHeight ](https://zeroheight.com/19c7d85e4/p/480bdf-changelog/b/38c3bc).
The survey components have 3 variants that can be use for client, they are emoji survey, stars rating survey, and simple survey with 2 option.

### Changes

-  Add new folder survey in library (setup and initialize package.json)
-  Add import '@tunaiku-ui-web/survey/survey.scss' in core index.scss for load the module
- Add the documentation in survey.mdx.

### User Interface
![screencapture-localhost-8000-components-survey-2023-02-16-15_21_55](https://user-images.githubusercontent.com/22863200/219311344-9678f4cb-acec-4c05-8653-a1dc8fcc4f8c.png)

2023-02-17 06:55 UTC, cakahlul requested changes
ada feedback. minta tolong cek dulu ya

2023-02-17 06:55 UTC, cakahlul commented on library/survey/scss/_variables.scss
> +$amb-content-gap: (
ini kalau ukurannya ikutin yg ada di file ini gimana? https://github.com/tunaiku/tunaiku-ui-web/blob/RPY-1216/library/spacing/scss/_variables.scss .

atau kalau memungkinkan, kita re-use aja spacing variablenya.

- [ ] adjust gap value

2023-02-17 06:55 UTC, cakahlul commented on library/survey/scss/_mixins.scss
> +      gap: $gap-value !important;
kalau pakai margin aja gabisa kah?

- [ ] question

2023-02-17 06:55 UTC, cakahlul commented on library/survey/scss/_mixins.scss
> +      font-weight: bold;
ini boldnya ga perlu ya. karena dari HTML nya bisa pakai class typography yang udah ada aja. kalau dipaksa bold gini nanti kurang dinamis jadinya. gimana?

- [ ] remove font-weight property (?)

2023-02-17 07:38 UTC, lekhasholehati commented on library/survey/scss/_mixins.scss
> +      gap: $gap-value !important;
@cakahlul bisa mas, saya perbaiki, jadinya saya ga nambahin modifier --gapSmall langsung pakai margin aja di survey-content--bordered

2023-02-17 07:40 UTC, lekhasholehati commented on library/survey/scss/_mixins.scss
> +      font-weight: bold;
@cakahlul  oke mas bisa harusnya pakai class typography

2023-02-20 04:39 UTC, cakahlul approved these changes

2023-02-24 06:25 UTC, Christian-007 approved these changes

2023-02-24 06:31 UTC, merged